### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by rikurauhala** [rikurauhala/rikurauhala.github.io#32]

**Comment by the-amazing-atharva** [comment]
Hi!

I would like to create the contributing.md file

**Comment by rikurauhala** [comment]
> Hi!
> 
> I would like to create the contributing.md file

Hello! If you wish to contribute, feel free to open a new pull request and suggest changes. I'm working on eventually making a more generalized version of this project that is not necessarily tied to my personal profile so it will be easier for anyone to make their own version by simply downloading the source code, filling in their own username and information and deploying to GitHub Pages.

**Comment by the-amazing-atharva** [comment]
Thanks for the reply

Will be sending a PR soon !!
Good luck with your project
